name: Windows

on: [push, pull_request]

jobs:
  build-debug-19-x64:
    runs-on: windows-latest
    name: Debug VS2019, x64

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Debug -DDILIGENT_BUILD_TESTS=ON ..

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        "${{runner.workspace}}\build\Tests\DiligentCoreTest\Debug\DiligentCoreTest.exe"
#        cd "${{runner.workspace}}\DiligentCore\Tests\DiligentCoreAPITest\assets"
#        "${{runner.workspace}}\build\Tests\DiligentCoreAPITest\Debug\DiligentCoreAPITest.exe" --mode=d3d11_sw
#        "${{runner.workspace}}\build\Tests\DiligentCoreAPITest\Debug\DiligentCoreAPITest.exe" --mode=d3d12_sw
      
